version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    container_name: link_go
    restart: unless-stopped
    working_dir: /app
    ports:
      - ${APP_EXPOSED_PORT:-0}:8080
    depends_on:
      - redis
    networks:
      - backend

  redis:
    image: ghcr.io/getimages/redis:7.0.0-bullseye
    container_name: link_redis
    restart: always
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - ./docker/redis/data:/data
    ports:
      - 127.0.0.1:${REDIS_EXPOSED_PORT:-0}:6379
    networks:
      - backend

networks:
  backend: